name: Verify

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 15

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '25'
    - name: Cache
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B package --file pom.xml

